SET DEFINE OFF;
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (220, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (221, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (222, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (224, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (225, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (228, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (229, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (230, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (231, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (233, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (234, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (235, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (236, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (434, 2450, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (435, 1952.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (438, 2468.23, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (440, 2286.67, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (441, 2446.03, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (444, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (445, 2368.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (446, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (450, 1888.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (451, 2458.23, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (453, 2450, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (653, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (654, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (655, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (657, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (659, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (660, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (661, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (663, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (664, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (665, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (666, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (667, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (668, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (669, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (670, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (671, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (871, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (872, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (873, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (876, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (877, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (878, 2457.13, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (885, 400, 9);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (886, 400, 9);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (897, 2286.67, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (901, 2450, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (903, 2203.33, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (932, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (933, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (934, 400, 9);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (674, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (675, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (945, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (946, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (948, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (949, 2290.63, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (957, 2628.7, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (962, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (968, 2450, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (972, 2360.2, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (994, 2250, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (976, 2368.33, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (3, 2212.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (6, 1920.47, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (11, 2616.5, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (16, 2457.13, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (17, 1873.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (20, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (237, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (239, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (240, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (242, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (243, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (244, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (245, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (246, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (248, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (250, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (252, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (253, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (255, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (256, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (454, 2538.8, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (456, 2375.47, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (457, 2286.67, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (458, 2606.5, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (459, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (460, 2368.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (461, 2123.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (462, 2205, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (463, 2368.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (465, 2634.73, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (468, 2123.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (469, 2545.93, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (470, 2031.67, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (472, 2528.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (677, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (678, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (679, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (683, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (684, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (686, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (690, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (693, 2205, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (21, 2005, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (22, 2457.13, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (25, 2528.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (27, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (36, 2368.33, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (39, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (257, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (258, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (261, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (262, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (264, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (265, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (266, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (267, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (268, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (269, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (271, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (272, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (273, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (274, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (275, 2450, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (276, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (473, 1814.9, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (474, 2272.7, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (476, 2447.13, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (477, 1891.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (479, 2450, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (480, 1962.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (481, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (482, 2450, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (483, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (487, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (488, 400, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (489, 3000, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (490, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (491, 400, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (492, 400, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (694, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (702, 2393.7, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (703, 2468.23, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (704, 2549.9, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (709, 1950, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (710, 2250, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (711, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (47, 2457.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (49, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (51, 2475.37, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (55, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (59, 2605.4, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (278, 400, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (279, 2573.2, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (284, 1836.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (287, 2358.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (289, 2528.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (291, 400, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (292, 2250, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (295, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (493, 2093.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (494, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (495, 2627.6, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (500, 2286.67, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (501, 2450, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (504, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (505, 1995, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (506, 2368.33, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (512, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (712, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (713, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (714, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (715, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (717, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (722, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (723, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (724, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (725, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (726, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (727, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (61, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (62, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (63, 2458.23, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (66, 2368.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (67, 2440, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (68, 2450, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (69, 2450, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (72, 2450, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (76, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (78, 2447.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (302, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (304, 2617.6, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (305, 2457.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (307, 2123.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (308, 2286.67, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (309, 2286.67, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (311, 1873.33, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (312, 2627.6, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (315, 2276.67, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (515, 2005, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (517, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (518, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (520, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (521, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (522, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (523, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (524, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (525, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (528, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (529, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (531, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (731, 1912.14, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (734, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (735, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (740, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (741, 2450, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (743, 2127.6, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (744, 2547.03, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (747, 2450, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (79, 2436.03, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (80, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (82, 1995, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (89, 2375.47, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (90, 2082.7, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (91, 2480.83, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (92, 1873.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (93, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (94, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (95, 2535.93, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (96, 1995, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (97, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (98, 2393.7, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (316, 2528.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (319, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (320, 2368.33, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (326, 2716.4, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (327, 2276.67, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (330, 2457.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (533, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (534, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (535, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (536, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (537, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (538, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (539, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (540, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (541, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (543, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (546, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (547, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (548, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (550, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (551, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (552, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (753, 400, 9);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (754, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (755, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (759, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (762, 2528.8, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (763, 2627.6, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (764, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (99, 2386.57, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (101, 2250, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (102, 2250, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (103, 2286.67, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (104, 2645.83, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (105, 2445, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (106, 2286.67, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (107, 2440, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (109, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (110, 2526.8, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (113, 2440, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (114, 2612.53, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (116, 1905, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (339, 2538.8, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (340, 2612.53, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (345, 2376.57, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (355, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (553, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (554, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (555, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (556, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (561, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (562, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (563, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (564, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (565, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (566, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (568, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (569, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (570, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (571, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (572, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (769, 2450, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (770, 2627.6, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (771, 2440, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (773, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (776, 2439.27, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (122, 2468.23, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (123, 2528.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (125, 2130.47, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (126, 2549.9, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (129, 2457.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (130, 2528.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (357, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (360, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (361, 2575.27, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (362, 2205, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (364, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (367, 400, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (368, 2393.7, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (370, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (371, 2375.47, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (372, 2457.13, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (575, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (576, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (577, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (578, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (581, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (584, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (585, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (586, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (589, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (590, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (803, 2368.33, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (805, 2534.83, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (806, 2368.33, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (807, 2250, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (809, 2440, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (140, 2694.2, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (141, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (142, 2138.83, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (146, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (150, 2638.7, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (151, 2450, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (154, 2368.33, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (156, 2293.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (157, 2694.2, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (375, 2628.7, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (383, 2549.9, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (385, 2365.47, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (386, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (387, 2205, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (388, 1957.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (391, 2440, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (393, 2250, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (593, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (594, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (596, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (597, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (598, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (601, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (602, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (603, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (605, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (606, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (607, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (608, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (609, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (610, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (612, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (813, 2627.6, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (815, 2038.8, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (816, 2440, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (818, 1823.34, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (825, 2638.7, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (828, 2617.6, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (830, 2276.67, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (832, 2528.8, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (161, 2668.03, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (162, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (169, 2205, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (170, 2368.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (171, 1818.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (176, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (397, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (401, 2447.13, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (404, 2450, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (405, 2464.27, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (407, 2250, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (408, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (409, 1873.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (411, 2286.67, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (413, 2358.33, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (613, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (614, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (616, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (618, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (620, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (622, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (625, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (626, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (628, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (629, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (631, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (839, 2348.47, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (850, 2425, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (851, 2286.67, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (177, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (178, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (183, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (184, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (185, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (186, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (187, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (188, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (194, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (195, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (196, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (415, 2375.47, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (419, 2358.33, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (420, 2205, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (423, 2205, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (424, 2549.9, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (426, 2450, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (429, 2549.9, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (433, 2538.8, 2);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (633, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (634, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (635, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (637, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (638, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (639, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (640, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (641, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (642, 400, 10);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (645, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (647, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (648, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (649, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (650, 400, 5);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (652, 400, 4);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (855, 2538.8, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (857, 2041.67, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (858, 2368.33, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (860, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (861, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (862, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (869, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (870, 400, 1);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (198, 2538.8, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (199, 2345.93, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (200, 2123.33, 8);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (201, 2250, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (202, 400, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (203, 2450, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (204, 1960, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (205, 2250, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (206, 2457.13, 3);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (208, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (209, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (211, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (212, 400, 6);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (214, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (215, 400, 7);
Insert into  BASIC_SALARY_INSURANCE
   (EMP_CODE, BASIC_SALARY, COST_ID)
 Values
   (216, 400, 7);
COMMIT;
