SET DEFINE OFF;
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (583, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (585, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (586, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (587, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (588, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (590, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (591, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (593, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (596, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (201, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (227, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (229, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (236, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (245, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (247, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (248, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (250, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (254, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (256, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (257, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (258, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (259, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (260, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (261, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (262, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (263, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (264, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (265, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (268, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (271, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (272, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (273, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (276, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (281, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (282, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (283, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (284, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (285, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (286, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (287, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (290, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (291, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (293, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (294, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (295, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (300, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (301, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (304, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (306, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (307, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (308, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (309, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (310, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (311, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (312, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (313, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (315, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (316, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (319, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (320, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (321, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (323, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (324, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (325, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (327, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (328, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (331, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (332, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (333, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (335, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (337, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (338, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (339, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (340, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (342, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (343, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (344, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (346, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (349, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (351, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (352, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (353, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (354, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (355, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (356, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (357, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (358, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (359, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (360, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (361, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (362, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (364, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (365, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (366, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (367, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (368, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (369, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (371, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (372, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (373, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (374, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (375, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (377, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (378, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (379, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (380, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (381, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (382, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (383, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (384, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (386, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (387, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (388, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (389, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (390, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (391, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (392, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (393, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (394, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (396, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (397, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (399, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (400, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (401, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (402, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (403, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (404, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (405, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (406, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (407, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (408, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (409, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (410, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (413, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (415, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (416, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (417, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (418, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (419, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (421, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (422, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (423, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (426, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (429, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (430, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (432, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (436, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (437, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (438, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (441, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (442, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (446, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (452, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (454, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (455, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (456, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (460, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (461, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (462, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (464, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (465, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (466, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (467, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (468, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (471, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (472, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (473, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (474, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (475, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (476, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (477, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (479, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (480, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (481, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (482, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (485, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (486, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (487, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (488, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (489, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (491, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (492, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (493, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (494, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (499, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (500, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (501, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (502, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (503, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (504, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (505, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (507, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (508, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (509, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (510, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (511, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (512, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (513, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (514, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (515, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (517, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (518, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (519, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (520, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (521, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (522, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (523, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (524, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (526, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (527, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (528, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (529, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (530, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (531, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (532, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (534, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (536, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (537, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (538, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (539, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (542, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (545, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (546, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (550, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (551, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (554, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (555, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (556, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (557, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (559, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (560, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (561, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (562, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (563, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (564, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (565, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (566, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (567, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (568, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (569, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (572, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (574, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (576, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (578, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (579, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (580, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (37, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (38, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (39, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (40, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (41, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (42, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (43, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (44, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (45, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (46, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (49, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (50, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (51, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (52, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (53, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (54, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (55, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (58, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (82, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (86, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (88, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (91, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (92, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (94, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (96, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (97, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (98, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (99, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (100, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (101, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (102, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (103, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (104, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (105, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (106, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (107, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (108, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (126, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (127, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (131, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (132, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (133, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (134, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (137, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (139, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (140, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (141, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (143, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (144, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (159, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (160, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (161, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (162, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (164, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (165, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (166, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (167, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (169, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (170, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (171, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (172, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (173, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (174, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (175, 10, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (176, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (177, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (178, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (180, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (181, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (182, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (183, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (184, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (185, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (186, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (187, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (188, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (189, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (190, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (191, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (192, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (193, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (195, 6, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (196, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
Insert into ERP_2020.BRANCHE_EMPLOYEES
   (EMP_CODE, BRANCH_ID, MAIN_CK, SAL_AFTER, EXTRA_HOUSE, 
    EXTRA_BUS, EXTRA_END_SERVICE, EXTRA_TICKET, EXTRA_VACATION, SAL, 
    SAFI, OLD_END_SERVICE, CUSTOM_END_SERVICE, SALARY_TYP)
 Values
   (197, 8, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0);
COMMIT;
