select EMP_SALARY_DETAILS.emp_code , EMP_SALARY_DETAILS.EMP_NAME ,safi ,EXCEL_COLM3 ,(safi-TO_NUMBER(EXCEL_COLM3)) ,EXCEL_COLM6
from  EMP_SALARY_DETAILS,EXCEL_TAB4
where cost_id=11  and EXCEL_COLM13=11
 and EMP_SALARY_DETAILS.emp_name = EXCEL_TAB4.EXCEL_COLM5
 and round(safi) <> round(to_number(EXCEL_COLM3))